# Generated by Django 3.1.3 on 2020-11-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201124_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='default_full_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
