# Generated by Django 3.1.4 on 2020-12-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofiles_default_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='default_email',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
