# Generated by Django 3.1.3 on 2020-11-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='sub_id',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
