# Generated by Django 3.1.3 on 2020-11-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('Recurring', models.CharField(max_length=255)),
                ('stripeSubscriptionId', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='StripeCustomer',
        ),
    ]
