# Generated by Django 3.1.3 on 2020-11-23 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20201123_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='stripePricekey',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
