# Generated by Django 3.1.3 on 2020-11-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptions_stripepricekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
            preserve_default=False,
        ),
    ]
