# Generated by Django 3.1.3 on 2020-11-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscriptions_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
