# Generated by Django 3.1.3 on 2020-11-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_reviews_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_subscription',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_id',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
